### PR TITLE
Design: Improve handling of invalid Unicode

### PR DESCRIPTION
**Pull request by CyberShadow**
The previously proposed design is not very good. I don't think any languages do what has been proposed here.

It can lead to silent data corruption, hard-to-detect bugs, and even possibly security issues. There is a long thread on Bugzilla on this subject.

I think what I proposed here is more sensible, and in line with what other languages (such as Rust) do.

### CODE REVIEW

**Comment by rikkimax** [comment]
This isn't just not done elsewhere, this is out right not compliant with the Unicode standard.

2.7 Unicode Strings:

> Whenever such strings are specified to be in a particular Unicode encoding form—even
one with the same code unit size—the string must not violate the requirements of that
encoding form. For example, isolated surrogates in a Unicode 16-bit string are not allowed
when that string is specified to be well-formed UTF-16. A number of techniques are available for dealing with an isolated surrogate, such as omitting it, converting it into U+FFFD
replacement character to produce well-formed UTF-16, or simply halting the processing of the string with an error. (See Section 3.9, Unicode Encoding Forms.)

**Comment by pbackus** [comment]
I don't think it makes sense for Phobos to assume that (e.g.) `string` is valid UTF-8 unless there are enforcement mechanisms in place to prevent invalid `string`s from being created.

Since adding such enforcement mechanisms to the compiler and library would be extremely disruptive to existing code, I think a better way forward here would be to add library types for Unicode strings that validate their data upon construction.

**Comment by schveiguy** [comment]
what does "abort the program" mean? In which cases will it abort? Surely e.g. assigning a string, or searching for a `char` in a string will not abort?

I would really suggest throwing an Error in this case instead of something like a divide-by-zero abort (which is typically a signal, and gives no stack trace).

**Comment by CyberShadow** [comment]
Normally, I would too. But the document also says exceptions are going away, and I don't know what will replace them. Presumably `assert(0)` will still do something like an abort.

**Comment by schveiguy** [comment]
assert(0) throws when built with asserts, and aborts when built without asserts.

> But the document also says exceptions are going away

WAT?

**Comment by CyberShadow** [comment]
> WAT?

https://github.com/LightBender/PhobosV3-Design/blob/main/Design.md#no-exceptions

???

**Comment by schveiguy** [comment]
I just mean, D has exceptions. I can agree with removing exceptions for trivialities, or providing alternative error handling. But *removing exceptions* from phobos completely seems like a huge leap backwards.

**Comment by rikkimax** [comment]
Realistically Unicode handling should throw an exceptional path error for malformed sequences.

This is the recommended way.

However, it shouldn't be able to kill the process without you infecting the entire call stack.

This would ideally be solved by my proposed value type exceptions.
Unfortunately, that depends upon sumtypes and Adam isn't keen on waiting for things to be ready in the language for stuff like ranges.

**Comment by schveiguy** [comment]
Reading the design document again, I think that the "No exceptions" title is more forceful than the text, which seems to say the goal is to remove each use of an exception *if possible*.

It also specifically talks about `@nogc` and `nothrow`, both of which are possible with throwing Errors.

I've never been sold on the `nothrow` performance benefits. But making things that are usable without throwing would benefit porting to new platforms, as exceptions are one of the more difficult things to add (I'm looking at WASM).

Using the replacement character by default seems like a much better option *only when decoding*. Why can't we strive for that? With the removal of autodecoding, decoding is explicit, and one can pick their poison. The only thing that remains would be the `foreach(dchar d; str)` which throws, but that's a language change, not a phobos change. Adam and I had a discussion on that at beerconf, I think that's more of a problem with implicit conversions as an underlying problem.

If we aren't going to create a more encapsulated `string` type, then I can't see how assuming valid utf is reasonable -- slicing a string in the middle of a utf code point is trivial and supported by the language.

**Comment by CyberShadow** [comment]
> Using the replacement character by default seems like a much better option _only when decoding_.

Yes, it should just be very explicit that you're getting the `x/0 == 0` flavor of error handling.

> If we aren't going to create a more encapsulated `string` type, then I can't see how assuming valid utf is reasonable -- slicing a string in the middle of a utf code point is trivial and supported by the language.

Ouch, I completely forgot about that. Good point.

**Comment by LightBender** [comment]
One thing that I can be absolutely sure of is that aborting the program on bad Unicode is a terrible idea. Consider the example of a web-server that handles multiple requests per process. If one malformed request causes all other in-process requests to be cancelled as the process crashes and recycles we create a terrible user experience for both the server programmers and their users. Additionally we will have inadvertently created a major Denial-of-Service attack vector.

Under no circumstance should malformed Unicode in an HTTP request be able to bring down an entire web application.

**Comment by CyberShadow** [comment]
👋 Hi, person who has written and maintained many, many web servers and web apps here, both as a hobbyist and professionally. If I made a bug where the only two choices are to crash the process or silently corrupt the data, please CRASH MY PROCESS. That is a lot easier to handle and clean up after than the possible consequences of silent lossy transformations of data handled by the process.

A crash will, in most circumstances, make the daemon supervisor log the crash and restart the process. Data corruption can propagate and multiply and go undetected for a long time.

I really think this case should be treated the same as integer division by zero, or dereferencing of a null pointer. We should make an effort to guide users in writing code that avoids the possibility of this situation arising, but if you do end up shooting yourself in the foot, e.g. by doing `cast(string)bytes` or a blind `str[1..$]`, then it's on the user.

**Comment by CyberShadow** [comment]
> I really think this case should be treated the same as integer division by zero, or dereferencing of a null pointer.

If we are removing autodecoding anyway, I think this is moot either way. The above is only a problem in ranges, which do not have an intrinsic mechanism to communicate errors (other than exceptions).

Updated diff.

**Comment by LightBender** [comment]
I think the updated diff is sufficient. Merging.

**Review by LightBender — APPROVED** [review]

**Comment by pbackus** [comment]
I've started a discussion about Unicode string types here: https://github.com/LightBender/PhobosV3-Design/discussions/25

**Pull request merged**
